### ISSUE TITLE
No file model_index.json is found

### ISSUE THREAD

**Issue by PavelBartenev** [davide97l/stable_diffusion_dreambooth_inpainting#1]
I am trying to run the Colab notebook stable_diffusion_dreambooth_inpaint.ipynb. While trying to generate images from finetuned model 
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "stable-diffusion-inpainting-dog",
    torch_dtype=torch.float16,
)

I am getting the error:

OSError                                   Traceback (most recent call last)
[<ipython-input-12-f5a17f456734>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 
----> 6 pipe = StableDiffusionInpaintPipeline.from_pretrained(
      7     "model",
      8     torch_dtype=torch.float16,

3 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py](https://localhost:8080/#) in load_config(cls, pretrained_model_name_or_path, return_unused_kwargs, return_commit_hash, **kwargs)
    368                 config_file = os.path.join(pretrained_model_name_or_path, subfolder, cls.config_name)
    369             else:
--> 370                 raise EnvironmentError(
    371                     f"Error no file named {cls.config_name} found in directory {pretrained_model_name_or_path}."
    372                 )

OSError: Error no file named model_index.json found in directory model.

**Comment by davide97l** [comment]
This error means that the model hasn't been trained, so its configuration files don't exist. Have you run the notebook cell by cell?
